packages:
  - apps/*
  - packages/*

nodeLinker: hoisted
autoInstallPeers: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/*'
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  electron-winstaller: false
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: false
patchedDependencies:
  '@deepseek-ai/dsh-session-format-v0-to-v1@0.1.5-rc.1': patches/@deepseek-ai__dsh-session-format-v0-to-v1@0.1.5-rc.1.patch
  '@deepseek-ai/dsh-client-ui-chat@0.1.5-rc.1': patches/@deepseek-ai__dsh-client-ui-chat@0.1.5-rc.1.patch
  '@deepseek-ai/dsh-llm-pi-ai@0.1.5-rc.1': patches/@deepseek-ai__dsh-llm-pi-ai@0.1.5-rc.1.patch
  '@deepseek-ai/dsh-llm-deepseek@0.1.5-rc.1': patches/@deepseek-ai__dsh-llm-deepseek@0.1.5-rc.1.patch
  '@deepseek-ai/dsh-client-ui-model-selection@0.1.5-rc.1': patches/@deepseek-ai__dsh-client-ui-model-selection@0.1.5-rc.1.patch
  '@deepseek-ai/dsh-api-session-controller@0.1.5-rc.1': patches/@deepseek-ai__dsh-api-session-controller@0.1.5-rc.1.patch
  '@deepseek-ai/dsh-tool-fs@0.1.5-rc.1': patches/@deepseek-ai__dsh-tool-fs@0.1.5-rc.1.patch
  '@deepseek-ai/dsh-agent-presets@0.1.5-rc.1': patches/@deepseek-ai__dsh-agent-presets@0.1.5-rc.1.patch
  '@deepseek-ai/dsh-sdk-minimal@0.1.5-rc.1': patches/@deepseek-ai__dsh-sdk-minimal@0.1.5-rc.1.patch
  '@deepseek-ai/dsh-client-ui-open-in-app@0.1.5-rc.1': patches/@deepseek-ai__dsh-client-ui-open-in-app@0.1.5-rc.1.patch
