packages:
  - apps/*
  - packages/*

nodeLinker: hoisted
autoInstallPeers: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/*'
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  electron-winstaller: false
  esbuild: true
  koffi: true
  node-pty: true
  protobufjs: false
patchedDependencies:
  '@deepseek-ai/dsh-api-session-controller@0.2.0-rc.2': patches/@deepseek-ai__dsh-api-session-controller@0.2.0-rc.2.patch
  '@deepseek-ai/dsh-llm-deepseek@0.2.0-rc.2': patches/@deepseek-ai__dsh-llm-deepseek@0.2.0-rc.2.patch
  '@deepseek-ai/dsh-llm-pi-ai@0.2.0-rc.2': patches/@deepseek-ai__dsh-llm-pi-ai@0.2.0-rc.2.patch
  '@deepseek-ai/dsh-session-format-v0-to-v1@0.2.0-rc.2': patches/@deepseek-ai__dsh-session-format-v0-to-v1@0.2.0-rc.2.patch
  '@deepseek-ai/dsh-tool-fs@0.2.0-rc.2': patches/@deepseek-ai__dsh-tool-fs@0.2.0-rc.2.patch
  '@deepseek-ai/dsh-web-app@0.2.0-rc.2': patches/@deepseek-ai__dsh-web-app@0.2.0-rc.2.patch
